#!/bin/sh
# ============================================================
# wireguard-ds124 一键安装脚本
# 用途: 拷贝 WireGuard 内核模块到 /lib/modules 并注册开机自启
# 适配: Synology DS124 (RTD1619B / ARM64) DSM 7.2.2, 内核 5.10.55+
# 用法: 将本脚本与 modules/*.ko 放在同一目录, 以 root 运行
# ============================================================

set -e

MODULE_SRC="$(dirname "$0")"
MODULE_DST="/lib/modules"
RCD_SCRIPT="/usr/local/etc/rc.d/wireguard-start.sh"

# 需要按顺序加载的模块
MODULES="
libblake2s
libcurve25519
libcurve25519-generic
libchacha
chacha-neon
poly1305-neon
libchacha20poly1305
libblake2s-generic
ip6table_nat
wireguard
"

echo "=============================================="
echo " WireGuard DS124 安装脚本"
echo " 源目录: $MODULE_SRC"
echo "=============================================="

# 1. 检查 root
if [ "$(id -u)" != "0" ]; then
    echo "[错误] 请以 root 身份运行 (sudo -i 或直接 root 登录)"
    exit 1
fi

# 2. 拷贝模块
echo "[1/4] 拷贝模块到 $MODULE_DST ..."
mkdir -p "$MODULE_DST"
for m in $MODULES; do
    if [ -f "$MODULE_SRC/$m.ko" ]; then
        cp -f "$MODULE_SRC/$m.ko" "$MODULE_DST/"
        echo "  ✓ $m.ko"
    else
        echo "  ⚠ 缺少 $m.ko (跳过)"
    fi
done

# 3. 加载模块
echo "[2/4] 加载模块 (按依赖顺序)..."
cd "$MODULE_DST"
for m in $MODULES; do
    if [ -f "$MODULE_DST/$m.ko" ]; then
        # 已加载则跳过, 未加载则 insmod
        if ! lsmod | grep -q "^${m} "; then
            insmod "$MODULE_DST/$m.ko" 2>/dev/null && echo "  ✓ $m.ko 已加载" \
                || echo "  ✗ $m.ko 加载失败"
        else
            echo "  ✓ $m.ko 已在内核中"
        fi
    fi
done

# 4. 注册开机自启
echo "[3/4] 写入开机自启脚本 $RCD_SCRIPT ..."
cat > "$RCD_SCRIPT" << EOF
#!/bin/sh
# WireGuard modules autoload - generated by install-wireguard.sh
# DSM boot script (runs at startup)
case \$1 in
    start)
        cd $MODULE_DST
        for m in $MODULES; do
            [ -f "$MODULE_DST/\$m.ko" ] && insmod "$MODULE_DST/\$m.ko" 2>/dev/null
        done
        ;;
    stop)
        rmmod wireguard 2>/dev/null || true
        ;;
esac
EOF
chmod +x "$RCD_SCRIPT"
echo "  ✓ $RCD_SCRIPT 已创建"

# 5. 验证
echo "[4/4] 验证 ..."
sleep 1
echo "--- lsmod 结果 ---"
lsmod | grep -E "wireguard|blake|chacha|curve|ip6table" || echo "(未找到相关模块)"
echo "--------------------"

if lsmod | grep -q "^wireguard "; then
    echo ""
    echo "✅ WireGuard 内核模块已成功加载!"
    echo "   现在可以启动 wg-easy 容器 (见 start-wg-easy.sh)"
else
    echo ""
    echo "❌ wireguard 模块未加载, 请检查上面的错误信息"
    echo "   常见原因: 内核版本不匹配 (请确认 DSM 为 7.2.2-72806, 内核 5.10.55+)"
fi
